# Generated by Django 5.1.7 on 2025-03-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
